"""empty message

Revision ID: dd7a8d608274
Revises: 
Create Date: 2024-02-22 13:42:06.339256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7a8d608274'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(), nullable=False, comment='密码'),
    sa.Column('email', sa.String(), nullable=True, comment='邮箱'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='public')
    # ### end Alembic commands ###
